spring:
  application:
    name: eqa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eqa?characterEncoding=utf-8&useSSL=false&useUnicode=true&serverTimezone=GMT%2B8
    username: root
    password: Ethan1128?
server:
  port: 30001
mybatis-plus:
  global-config:
    db-config:
      # 逻辑删除配置
      logic-delete-field: deleted # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  # 指定在编译产物中的哪里寻找 mapper 的 xml 配置文件（classpath 指代 target/classes 目录）
  mapper-locations: classpath:com/ethan/qa/mapper/xml/*.xml